development:
  adapter: postgresql
  encoding: unicode
  database: rspec_example_dev
  pool: 5
  username: jamesnewman
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: rspec_example_test
  pool: 5
  username: jamesnewman
  password: password
